# Some covid stats

In [1]:
import pandas
import numpy as np
pandas.set_option('display.max_rows', None)

In [2]:
df = pandas.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-23-2020.csv')
df['Confirmed'] = df['Confirmed'].astype(int)
df['Deaths'] = df['Deaths'].astype(int)
df['Recovered'] = df['Recovered'].astype(int)
print(df['Deaths'].sum())
df = df[df['Country_Region'] == 'US']

342097

In [3]:
def render_grouping(col):
    df2 = df.groupby(col).sum().sort_values(by=['Deaths'], ascending=False)
    df2["Row #"] = np.arange(len(df2)) + 1
    return df2.filter(items=['Row #', 'Confirmed', 'Deaths', 'Recovered'])

Here we have grouped by US state

In [4]:
render_grouping('Province_State')

                          Row #  Confirmed  Deaths  Recovered
Province_State
New York                      1     359926   29031          0
New Jersey                    2     153140   11082          0
Massachusetts                 3      91662    6304          0
Michigan                      4      54365    5223          0
Pennsylvania                  5      71009    5112          0
Illinois                      6     107796    4790          0
California                    7      92539    3738          0
Connecticut                   8      40022    3675          0
Louisiana                     9      36925    2668          0
Maryland                     10      45495    2243          0
Florida                      11      50127    2233          0
Indiana                      12      30901    1964          0
Ohio                         13      31408    1956          0
Georgia                      14      42242    1822          0
Texas                        15      54776    1478          0
Colorado                     16      23964    1327          0
Virginia                     17      35749    1159          0
Washington                   18      19265    1050          0
Minnesota                    19      19845     861          0
Arizona                      20      16053     801          0
North Carolina               21      22864     778          0
Missouri                     22      11966     682          0
Mississippi                  23      13005     616          0
Rhode Island                 24      13952     597          0
Alabama                      25      14117     549          0
Wisconsin                    26      14877     507          0
Iowa                         27      16898     446          0
District of Columbia         28       7966     427          0
South Carolina               29       9895     425          0
Kentucky                     30       8571     391          0
Nevada                       31       7526     387          0
Tennessee                    32      19785     329          0
Delaware                     33       8529     322          0
Oklahoma                     34       5960     311          0
New Mexico                   35       6625     302          0
New Hampshire                36       4089     208          0
Kansas                       37       8946     205          0
Nebraska                     38      11963     147          0
Oregon                       39       3888     147          0
Puerto Rico                  40       3100     127          0
Arkansas                     41       5775     115          0
Utah                         42       8260      97          0
Idaho                        43       2595      79          0
Maine                        44       2013      77          0
West Virginia                45       1705      72          0
Vermont                      46        954      54          0
North Dakota                 47       2365      52          0
South Dakota                 48       4464      50          0
Hawaii                       49        643      17          0
Montana                      50        479      16          0
Wyoming                      51        813      12          0
Alaska                       52        407      10          0
Virgin Islands               53         69       6          0
Guam                         54        165       5          0
Grand Princess               55        103       3          0
Northern Mariana Islands     56         22       2          0
Recovered                    57          0       0     361239
Diamond Princess             58         49       0          0

Grouping by us cities

In [5]:
render_grouping('Combined_Key')[0:50]

,Row #,Confirmed,Deaths,Recovered
Combined_Key,,,,
"New York City, New York, US",1,197266,21138,0
"Cook, Illinois, US",2,70417,3246,0
"Wayne, Michigan, US",3,19697,2361,0
"Los Angeles, California, US",4,44121,2092,0
"Nassau, New York, US",5,39726,2087,0
"Suffolk, New York, US",6,38802,1822,0
"Essex, New Jersey, US",7,17160,1589,0
"Bergen, New Jersey, US",8,17668,1521,0
"Middlesex, Massachusetts, US",9,20232,1512,0
"Westchester, New York, US",10,32881,1327,0
"Philadelphia, Pennsylvania, US",11,21234,1233,0
"Fairfield, Connecticut, US",12,14989,1208,0
"Hartford, Connecticut, US",13,9545,1169,0
"Hudson, New Jersey, US",14,18959,1138,0
"Union, New Jersey, US",15,15186,1022,0
"Oakland, Michigan, US",16,8192,954,0
"Middlesex, New Jersey, US",17,15215,942,0
"New Haven, Connecticut, US",18,10847,897,0
"Passaic, New Jersey, US",19,15610,888,0
"Essex, Massachusetts, US",20,13334,848,0
"Suffolk, Massachusetts, US",21,17291,827,0
"Macomb, Michigan, US",22,6482,778,0
"Norfolk, Massachusetts, US",23,7759,774,0
"Ocean, New Jersey, US",24,8316,686,0
"Worcester, Massachusetts, US",25,10251,667,0
"Montgomery, Pennsylvania, US",26,6464,633,0
"Miami-Dade, Florida, US",27,16694,629,0
"Rockland, New York, US",28,12934,618,0
"Unassigned, Rhode Island, US",29,1504,597,0
"Morris, New Jersey, US",30,6192,590,0
"Monmouth, New Jersey, US",31,7720,551,0
"Montgomery, Maryland, US",32,9699,550,0
"King, Washington, US",33,7669,542,0
"Hampden, Massachusetts, US",34,5621,541,0
"Marion, Indiana, US",35,9040,531,0
"Hennepin, Minnesota, US",36,6649,524,0
"Delaware, Pennsylvania, US",37,6114,513,0
"Plymouth, Massachusetts, US",38,7480,501,0
"Orleans, Louisiana, US",39,6944,500,0
"Prince George's, Maryland, US",40,13324,484,0
"Erie, New York, US",41,5552,480,0
"Bucks, Pennsylvania, US",42,4839,460,0
"Mercer, New Jersey, US",43,6351,447,0
"Jefferson, Louisiana, US",44,7232,432,0
"Orange, New York, US",45,10197,429,0
"District of Columbia, District of Columbia, US",46,7966,427,0
"Somerset, New Jersey, US",47,4425,397,0
"St. Louis, Missouri, US",48,4472,384,0
"Maricopa, Arizona, US",49,8177,383,0
"Bristol, Massachusetts, US",50,6426,362,0