# Some covid stats

In [1]:
import pandas
import numpy as np
pandas.set_option('display.max_rows', None)

In [2]:
df = pandas.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-14-2020.csv')
df['Confirmed'] = df['Confirmed'].astype(int)
df['Deaths'] = df['Deaths'].astype(int)
df['Recovered'] = df['Recovered'].astype(int)
print(df['Deaths'].sum())
df = df[df['Country_Region'] == 'US']

302418

In [3]:
def render_grouping(col):
    df2 = df.groupby(col).sum().sort_values(by=['Deaths'], ascending=False)
    df2["Row #"] = np.arange(len(df2)) + 1
    return df2.filter(items=['Row #', 'Confirmed', 'Deaths', 'Recovered'])

Here we have grouped by US state

In [7]:
render_grouping('Province_State')

                          Row #  Confirmed  Deaths  Recovered
Province_State
New York                      1     343051   27641          0
New Jersey                    2     142704    9946          0
Massachusetts                 3      82182    5482          0
Michigan                      4      49582    4787          0
Pennsylvania                  5      63105    4288          0
Illinois                      6      87937    3928          0
Connecticut                   7      35464    3219          0
California                    8      74871    3052          0
Louisiana                     9      33489    2417          0
Florida                      10      43210    1875          0
Maryland                     11      35903    1866          0
Indiana                      12      26053    1646          0
Georgia                      13      35977    1545          0
Ohio                         14      26357    1534          0
Texas                        15      44480    1235          0
Colorado                     16      20838    1086          0
Washington                   17      17773     983          0
Virginia                     18      27813     956          0
Minnesota                    19      13435     672          0
North Carolina               20      16968     641          0
Arizona                      21      12674     624          0
Missouri                     22      10594     566          0
Mississippi                  23      10483     480          0
Alabama                      24      11101     473          0
Rhode Island                 25      12016     468          0
Wisconsin                    26      11275     434          0
South Carolina               27       8189     371          0
District of Columbia         28       6736     358          0
Nevada                       29       6504     333          0
Kentucky                     30       7225     328          0
Iowa                         31      13675     318          0
Tennessee                    32      16699     287          0
Oklahoma                     33       4963     284          0
Delaware                     34       7223     260          0
New Mexico                   35       5503     242          0
Kansas                       36       7705     189          0
New Hampshire                37       3382     151          0
Oregon                       38       3479     137          0
Puerto Rico                  39       2427     117          0
Nebraska                     40       9260     103          0
Arkansas                     41       4366      98          0
Utah                         42       6749      75          0
Idaho                        43       2351      72          0
Maine                        44       1565      69          0
West Virginia                45       1427      60          0
Vermont                      46        932      53          0
South Dakota                 47       3792      43          0
North Dakota                 48       1712      40          0
Hawaii                       49        637      17          0
Montana                      50        462      16          0
Alaska                       51        383      10          0
Wyoming                      52        701       7          0
Virgin Islands               53         69       6          0
Guam                         54        152       5          0
Grand Princess               55        103       3          0
Northern Mariana Islands     56         19       2          0
Recovered                    57          0       0     246414
Diamond Princess             58         49       0          0

Grouping by us cities

In [8]:
render_grouping('Combined_Key')[0:50]

,Row #,Confirmed,Deaths,Recovered
Combined_Key,,,,
"New York City, New York, US",1,188545,20406,0
"Cook, Illinois, US",2,58457,2675,0
"Wayne, Michigan, US",3,18770,2183,0
"Nassau, New York, US",4,38743,2016,0
"Los Angeles, California, US",5,35392,1711,0
"Suffolk, New York, US",6,37544,1697,0
"Essex, New Jersey, US",7,15905,1496,0
"Bergen, New Jersey, US",8,17080,1423,0
"Middlesex, Massachusetts, US",9,18381,1327,0
"Westchester, New York, US",10,31792,1256,0
"Fairfield, Connecticut, US",11,13836,1093,0
"Hudson, New Jersey, US",12,17602,1032,0
"Philadelphia, Pennsylvania, US",13,19093,1008,0
"Hartford, Connecticut, US",14,7935,999,0
"Union, New Jersey, US",15,14385,930,0
"Oakland, Michigan, US",16,7952,888,0
"Middlesex, New Jersey, US",17,14332,841,0
"Passaic, New Jersey, US",18,14887,802,0
"New Haven, Connecticut, US",19,9712,767,0
"Suffolk, Massachusetts, US",20,15881,759,0
"Macomb, Michigan, US",21,6232,728,0
"Essex, Massachusetts, US",22,11950,725,0
"Norfolk, Massachusetts, US",23,7258,696,0
"Ocean, New Jersey, US",24,7742,595,0
"Rockland, New York, US",25,12596,594,0
"Montgomery, Pennsylvania, US",26,5583,587,0
"Morris, New Jersey, US",27,5954,539,0
"Miami-Dade, Florida, US",28,14742,535,0
"Worcester, Massachusetts, US",29,8555,524,0
"King, Washington, US",30,7290,519,0
"Hampden, Massachusetts, US",31,4974,487,0
"Orleans, Louisiana, US",32,6768,482,0
"Monmouth, New Jersey, US",33,7164,480,0
"Unassigned, Rhode Island, US",34,1227,468,0
"Marion, Indiana, US",35,7793,451,0
"Delaware, Pennsylvania, US",36,5252,448,0
"Hennepin, Minnesota, US",37,4331,441,0
"Montgomery, Maryland, US",38,7548,437,0
"Plymouth, Massachusetts, US",39,6774,435,0
"Jefferson, Louisiana, US",40,6860,423,0
"Orange, New York, US",41,9771,403,0
"Erie, New York, US",42,4671,400,0
"Prince George's, Maryland, US",43,10449,398,0
"Bucks, Pennsylvania, US",44,4248,395,0
"Mercer, New Jersey, US",45,5612,374,0
"District of Columbia, District of Columbia, US",46,6736,358,0
"Somerset, New Jersey, US",47,4159,348,0
"St. Louis, Missouri, US",48,4104,305,0
"Bristol, Massachusetts, US",49,5440,297,0
"Maricopa, Arizona, US",50,6599,292,0